### ISSUE TITLE
What does the "Enable Tunneling" feature do? 

### ISSUE THREAD

**Issue by Harmonie666** [theothernt/AerialViews#29]
It's enabled by default. 
I disabled it now, but didn't notice a difference.
What does it do? :)

**Comment by theothernt** [comment]
When I was modifying the app to add new features I had to research about 4K HDR playback and how it works on Android, what are the issues etc.

Tunneling is an option to use hardware acceleration for video decoding. And as there are lots of different Android devices, the same settings don't work for all. Tunneling was recommended, which is why it's on by default, but I add options to disable it just in case - but as you've seen, it shouldn't make a difference for 99% of people.

This is one of the [posts about tunneling and ExoPlayer](https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d) I read a while back.
