### ISSUE TITLE
Render Output 1080p on 4K

### ISSUE THREAD

**Issue by kravena** [theothernt/AerialViews#37]
I'm using an LG CX tv with a Shield TV (2019) which supports nearly everything and the app shows :

Render Output : 1920x1080@59.94006
Physical output : 3840x2160@59.94006

Also codec summary :

AVC : Found
HEVC : Not Found
Dolby vision: Not Found

------

As the tv shows the Dolby Vision pop up, even though the app suggests otherwise, are the screensavers being rendered in 4K? Or is the app ignoring all of the above?

I did try checking the EXCEED RENDER CAPBILITIES, but the output appeared the same.

![image](https://user-images.githubusercontent.com/16151488/147752042-619af8bd-8abe-432c-acf1-193a4141410b.jpeg)

**Comment by theothernt** [comment]
Apologies about the confusion on the Capabilities screen. It was designed to help people understand why certain videos were not playing... but it's not 100% accurate yet, and causes confusion 🙃

For starters, with the combination of an LG CX and Nvidia Shield, you can play both the 1080p and 4K Dolby Vision videos no problem.

The issue with the codecs is down to an assumption I had, which has now been proved wrong. Basically, the codecs have different names on different devices. It should be fixed in a couple of weeks.

The resolution issue is a strange one, but I will be updating the labels to make more sense. Basically, Android TV draws the app UI (buttons, text, etc) at 1080p. If you have a 4K TV, the UI is scaled up from that. Except for video. For video, the 'surface' that shows the video is 1:1 with the 'physical output' so it's 4K. I hope that makes sense!

(4K app UIs are finally possible in Android TV 12 but it might be a long time before we see that - Google TV runs v10, Shield is getting v11 in the next month or two)

**Comment by kravena** [comment]
This is exactly what I had hoped.

Ignore the capabilities screen, the video is rendered at the maximum capability at all times (dependant on the source video settings and the output settings of the device).

Thank you for the fast response.
