### ISSUE TITLE
Feature request: Save streamed videos locally / to share.

### ISSUE THREAD

**Issue by FaberfoX** [theothernt/AerialViews#38]
As you already have the playing from local / share functionality implemented, maybe add a way to save the videos, so that your app can re use them after a while instead of downloading / streaming them again?

Btw, congrats on the Play Store release!

**Comment by theothernt** [comment]
I had looked into that but there are a number of issues...

1. Most Android TVs, devices, etc have very little free storage. Obviously you can plug a USB key into most but that's tricky with the Google TV, for example, as you'd need a USB Type-C hub, etc - so it's not that it's impossible, it's just not most people aren't likely to do that, in my experience.
2. The screensaver app itself doesn't run for very long so it'd be hard to guarantee that a download would be successful. In fact, a previous version of Aerial Dream had this feature but it was removed due to issues.

There are probably a few more but it's something I decided against early on. At this stage, it's more likely i'll just make a screen where I list all videos, you check the videos you want, and it downloads them... not sure when I'll get around to that though!

And thanks, I hope the app works well and is stable - lots more work to do! ... and I'm always happy to hear more feature requests, discussions, etc - there are lots of little things I miss or didn't think of!
