### ISSUE TITLE
Playing videos on Network Share even when that option is switched off

### ISSUE THREAD

**Issue by Diddz79** [theothernt/AerialViews#42]
Have an odd issue on my main Shield TV Pro 2019.  I have an external 1TB USB 3 drive connected to the Shield an am using that drive as Shared Storage.  On that drive, I have each of the Apple Aeriel screen savers in a folder called screen savers.

Have this same setup on my other 2 Shields as well (another Pro and a Tube) and it works perfectly.  I deselect to Stream Apple Videos, and check off the box to play local videos via USB.  I leave the SMB share un-checked.  On my other Pro and Tube, this allows the app to work perfectly and play only the saved videos from the connected media (USB drive and SD card).

On my main 2019 Pro, though, I have the same 1 TB USB drive connected with the vdeos saved on it and also the same settings.  The only box that is checked is to play videos connected to the device via USB, etc.  I also have an SMB share connected to this Pro as my Plex server.  That SMB share is NAS storage where I keep my videos.  Even with the "Play videos from SMB Share" uncheck in the app, the app is playing movies from the SMB share when the screen saver comes on.  It's not playing any of the ariel vids I have saved on the attached storage.  No matter what settings I try, I can't get it to stop doing this.

Would it be possible to add an option to app to tell it where to point to in order to play videos?  This would elimiate the guess work of the app trying to do it by itself if we could just point it to a directory and tell it to play only these videos.

Thanks so much for the app.  It's really great!

**Comment by theothernt** [comment]
The issue you're running into is unique to the Shield as it can mount an SMB share (I don't think any other Android TV devices can). To an app, it looks like part of the local filesystem which is why it's playing the movies from your NAS.

There is a quick fix assuming you didn't rename any of the Apple videos you downloaded. Look in _Settings > Interface > Ignore unknown videos_

This setting isn't obvious as I have a lot of work to do in making the app easier to use, have more options etc. The will be to have something like...

* Apple Videos: OFF or 102 found, streaming remotely
* Local Videos: OFF or 20 found (180 non-Apple videos ignored)
* Network Videos: etc...

**Comment by Diddz79** [comment]
That worked!  Thanks so much!
