### ISSUE TITLE
Error while playing videos

### ISSUE THREAD

**Issue by Stackedstudio** [theothernt/AerialViews#64]
Normally waited for the screensaver to start

Took a long time to load. Showed "Error while playing <screensaver file name>.mov" and then starts the screensaver
Not just once but multiple times even after clearing data.

Device: Sony TV (Bravia A8H) running Android Pie.

**Comment by theothernt** [comment]
What type of videos are you trying to play?

Also, do you see the error message often?

**Comment by Stackedstudio** [comment]
The issue seems to be solved now and I did nothing to fix it.. I was playing "Apple TV Videos (Stream Apple videos Directly)"

**Comment by Stackedstudio** [comment]
`Error while trying to play https://syla....`. Some url is displayed, probably videos URL.. different urls are shown. 
The error message is shown everytime I play manually from the `Test screensaver settings` option and sometimes when the screensaver starts automatically. Most of the time it takes a long time to load and gets stuck after a few seconds of playing.

**Comment by theothernt** [comment]
Ok, thanks. I'll probably turn off the error message in the next version.

If your TV has a free USB port, you could download the videos to a USB stick - playback should be a lot more reliable then?

**Comment by Stackedstudio** [comment]
Thanks for Responding!
the `Apple Videos` still sometimes get stuck just like before (you may open the issue again). My network is Average 46 Megabits per second. Larger Buffer either makes the loading longer or doesn't help

There are 110 Screensavers and each of them are over a gigabyte large so Its not worth downloading all of them in my opinion.
`It would be cool if Aerial Views could detect low network, and then load any of the offline videos randomly first (only if network is low)`

Then I could Keep 8-10 screensavers offline and this would make screensavers start super fast.
Another way could be Caching the videos automatically like the original TvOS


---
Different feature :
There could be an option to add Videos through URLs
A user can use Google TV app for copy-pasting URL via Android TV Remote feature 

---
I am waiting eagerly waiting for `'Select specific offline videos folder'` and the `'Auto-hide Location name ' & 'Dark transparent Location name Background'` features just like the Original TvOS.. I hope you do it soon!

Thank you @theothernt

**Comment by theothernt** [comment]
> Even with Larger Buffer, screensaver gets stuck.. a new issue is that almost every screensaver stays stuck after 2-4 seconds of playing and then changes to next screensaver video.. then same thing happens in loop (regardless of the buffer size)

This does point to it being an issue with your internet connection, and not something I can fix.

As I mentioned on the previous issue, your connection might be fast enough but the connection to Apple's CDN might be lower, or this is high latency or inconsistency on your connection.

> There are 110 Screensavers and each of them are over a gigabyte large so Its not worth downloading all of them in my opinion.

Then download a few you like, and add more over time.

> It would be cool if Aerial Views could detect low network, and then load any of the offline videos randomly first (only if network is low)

It's not possible to do this in any useful way for the app. Detecting connection speed and issues takes **time** (multiple seconds), which would slow down video playback even more.

It's also important to know that these videos are not streaming videos like YouTube or Netflix, so the quality cannot be adjusted in real-time to adjust to network conditions. That's why downloading the videos is the best option here.

> Then I could Keep 8-10 screensavers offline and this would make screensavers start super fast. Another way could be Caching the videos automatically like the original TvOS

This would not fix the issue, only delay it. A cached video would play, then if you next video was streamed you would see pauses and buffering. The next video **is not** buffered in advance.

> Different feature : There could be an option to add Videos through URLs A user can use Google TV app for copy-pasting URL via Android TV Remote feature

This is something that may appear in future, but I'm not certain yet.

> I am waiting eagerly waiting for `'Select specific offline videos folder'` and the `'Auto-hide Location name after few seconds' & 'Dark transparent gradient Background near the bottom'` features just like the Original TvOS. I hope you make it soon! `Also in the original Apple Screensavers, the Location names are displayed on the left` 

1. The folder feature already exists in the form of a **filter**. If you put videos in a folder called `/Aerial` then set the filter to that name, only those videos will play.
2. A similar feature to the Apple TV, as you describe, is in development although don't expect it to be exactly the same as Apple's version.

**Comment by Stackedstudio** [comment]
Thank you for replying, is it possible to add 'advance buffering of next video' as experimental feature?

> 2. A similar feature to the Apple TV, as you describe, is in development although don't expect it to be exactly the same as Apple's version.

Nice to know about it!

**Comment by theothernt** [comment]
> Thank you for replying, is it possible to add 'advance buffering of next video' as experimental feature?

Yes, but it might be a few months away. The whole video player has to be re-written so it's a lot of work.
