### ISSUE TITLE
Multi Onvif IP Camera Screen Saver Feed

### ISSUE THREAD

**Issue by dvaguirre** [theothernt/AerialViews#88]
I use several IP Cameras with IP Camera View app as Roku screen saver. I dont have anything like "IP Camera View" app on my Android TV devices.

**Comment by theothernt** [comment]
When using the screensaver to view IP camera feeds, what kind of features would you expect...

1. Camera feed should change every X seconds?
2. Change the camera feed manually with the dpad?

**Comment by dvaguirre** [comment]
Flexibility ll be nice, but split screen in 4 would be ok. 

I think that dpad wont work because would stop screen saver.

For example, 16 cams, screen splited in 4, changing to next 4 cams in X secs and/or full screen in cam with motion start for X secs after motion stops. If more than 1 cam start motion at same time, split screen in 4 with cameras on motion. 

ps: h265 compatibility is a plus, that dont work with Rokus's IP camera Viewer

ps2: secondary stream on idle (less FPS, less resolution, less bandwith, less decode resources) and primary stream on montion would be a huge plus.

**Comment by theothernt** [comment]
So the only issue is having 4 videos playing at the same time. It is possible, but for my screensaver I'm not sure when or if it'll be added.

Also, my app doesn't have an ability to add your own videos playlist of video streams - that might appear in the next month or two.

It is possible to use the dpad, it's just that nearly all screensavers don't - my app currently uses it to skip videos.

H.265 is dependant on the Android TV hardware but it's been common since 2015, I think.
